name: .NET Framework CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore Background_Working_Startup_Toast.sln

    - name: Build
      run: msbuild /p:Configuration=Release Background_Working_Startup_Toast.sln

    # If you have tests to run, uncomment the following lines
    # - name: Setup VSTest.console
    #   run: |
    #     echo "Adding VSTest to PATH"
    #     echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    # - name: Run tests
    #   run: vstest.console.exe YourTestProject.dll
